project:
  type: website

website:
  title: "Christian Gutierrez-Garcia"
  site-url: https://gutichris18.github.io/portfolio-website/
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: digital-marketing-projects.qmd
        text: Digital Marketing Projects
      - href: marketing-analytics-projects.qmd
        text: Marketing Analytics Projects
      - href: resume.qmd
        text: Resume
      - href: website-analytics.qmd
        text: GA4
      - href: Presentation.qmd
        text: Presentation

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: right
    page-layout: full
    css: styles.css

